//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace RestaurantOtomasyonu_ElTerminali.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tbl_Kullanicilar", Namespace="http://schemas.datacontract.org/2004/07/ElTerminaliService")]
    public partial class Tbl_Kullanicilar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresField;
        
        private System.Nullable<int> IDField;
        
        private string IsimField;
        
        private string KullaniciAdiField;
        
        private System.Nullable<int> KullaniciIDField;
        
        private string SifreField;
        
        private string SoyisimField;
        
        private System.Nullable<int> YetkiIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyisim {
            get {
                return this.SoyisimField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyisimField, value) != true)) {
                    this.SoyisimField = value;
                    this.RaisePropertyChanged("Soyisim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YetkiID {
            get {
                return this.YetkiIDField;
            }
            set {
                if ((this.YetkiIDField.Equals(value) != true)) {
                    this.YetkiIDField = value;
                    this.RaisePropertyChanged("YetkiID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElTerminali", Namespace="http://schemas.datacontract.org/2004/07/ElTerminaliService")]
    public partial class ElTerminali : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AciklamaField;
        
        private int AdetField;
        
        private string AdresField;
        
        private string AltMenuAdiField;
        
        private string EkIsteklerField;
        
        private int FiyatField;
        
        private int GenelToplamField;
        
        private string IsimField;
        
        private string MenuAdiField;
        
        private System.DateTime SiparisZamaniField;
        
        private string SoyisimField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Adet {
            get {
                return this.AdetField;
            }
            set {
                if ((this.AdetField.Equals(value) != true)) {
                    this.AdetField = value;
                    this.RaisePropertyChanged("Adet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltMenuAdi {
            get {
                return this.AltMenuAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AltMenuAdiField, value) != true)) {
                    this.AltMenuAdiField = value;
                    this.RaisePropertyChanged("AltMenuAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EkIstekler {
            get {
                return this.EkIsteklerField;
            }
            set {
                if ((object.ReferenceEquals(this.EkIsteklerField, value) != true)) {
                    this.EkIsteklerField = value;
                    this.RaisePropertyChanged("EkIstekler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((this.FiyatField.Equals(value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenelToplam {
            get {
                return this.GenelToplamField;
            }
            set {
                if ((this.GenelToplamField.Equals(value) != true)) {
                    this.GenelToplamField = value;
                    this.RaisePropertyChanged("GenelToplam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuAdi {
            get {
                return this.MenuAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuAdiField, value) != true)) {
                    this.MenuAdiField = value;
                    this.RaisePropertyChanged("MenuAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SiparisZamani {
            get {
                return this.SiparisZamaniField;
            }
            set {
                if ((this.SiparisZamaniField.Equals(value) != true)) {
                    this.SiparisZamaniField = value;
                    this.RaisePropertyChanged("SiparisZamani");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyisim {
            get {
                return this.SoyisimField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyisimField, value) != true)) {
                    this.SoyisimField = value;
                    this.RaisePropertyChanged("Soyisim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/KullaniciGirisi", ReplyAction="http://tempuri.org/IService1/KullaniciGirisiResponse")]
        System.IAsyncResult BeginKullaniciGirisi(string KullaniciAdi, string Sifre, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.Tbl_Kullanicilar> EndKullaniciGirisi(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SiparisBul", ReplyAction="http://tempuri.org/IService1/SiparisBulResponse")]
        System.IAsyncResult BeginSiparisBul(bool WebSiparisMi, bool TahsilatDurumu, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.ElTerminali> EndSiparisBul(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciGirisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public KullaniciGirisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.Tbl_Kullanicilar> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.Tbl_Kullanicilar>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiparisBulCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SiparisBulCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.ElTerminali> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.ElTerminali>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1>, RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginKullaniciGirisiDelegate;
        
        private EndOperationDelegate onEndKullaniciGirisiDelegate;
        
        private System.Threading.SendOrPostCallback onKullaniciGirisiCompletedDelegate;
        
        private BeginOperationDelegate onBeginSiparisBulDelegate;
        
        private EndOperationDelegate onEndSiparisBulDelegate;
        
        private System.Threading.SendOrPostCallback onSiparisBulCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<KullaniciGirisiCompletedEventArgs> KullaniciGirisiCompleted;
        
        public event System.EventHandler<SiparisBulCompletedEventArgs> SiparisBulCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1.BeginKullaniciGirisi(string KullaniciAdi, string Sifre, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginKullaniciGirisi(KullaniciAdi, Sifre, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.Tbl_Kullanicilar> RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1.EndKullaniciGirisi(System.IAsyncResult result) {
            return base.Channel.EndKullaniciGirisi(result);
        }
        
        private System.IAsyncResult OnBeginKullaniciGirisi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string KullaniciAdi = ((string)(inValues[0]));
            string Sifre = ((string)(inValues[1]));
            return ((RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1)(this)).BeginKullaniciGirisi(KullaniciAdi, Sifre, callback, asyncState);
        }
        
        private object[] OnEndKullaniciGirisi(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.Tbl_Kullanicilar> retVal = ((RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1)(this)).EndKullaniciGirisi(result);
            return new object[] {
                    retVal};
        }
        
        private void OnKullaniciGirisiCompleted(object state) {
            if ((this.KullaniciGirisiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KullaniciGirisiCompleted(this, new KullaniciGirisiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KullaniciGirisiAsync(string KullaniciAdi, string Sifre) {
            this.KullaniciGirisiAsync(KullaniciAdi, Sifre, null);
        }
        
        public void KullaniciGirisiAsync(string KullaniciAdi, string Sifre, object userState) {
            if ((this.onBeginKullaniciGirisiDelegate == null)) {
                this.onBeginKullaniciGirisiDelegate = new BeginOperationDelegate(this.OnBeginKullaniciGirisi);
            }
            if ((this.onEndKullaniciGirisiDelegate == null)) {
                this.onEndKullaniciGirisiDelegate = new EndOperationDelegate(this.OnEndKullaniciGirisi);
            }
            if ((this.onKullaniciGirisiCompletedDelegate == null)) {
                this.onKullaniciGirisiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKullaniciGirisiCompleted);
            }
            base.InvokeAsync(this.onBeginKullaniciGirisiDelegate, new object[] {
                        KullaniciAdi,
                        Sifre}, this.onEndKullaniciGirisiDelegate, this.onKullaniciGirisiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1.BeginSiparisBul(bool WebSiparisMi, bool TahsilatDurumu, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSiparisBul(WebSiparisMi, TahsilatDurumu, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.ElTerminali> RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1.EndSiparisBul(System.IAsyncResult result) {
            return base.Channel.EndSiparisBul(result);
        }
        
        private System.IAsyncResult OnBeginSiparisBul(object[] inValues, System.AsyncCallback callback, object asyncState) {
            bool WebSiparisMi = ((bool)(inValues[0]));
            bool TahsilatDurumu = ((bool)(inValues[1]));
            return ((RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1)(this)).BeginSiparisBul(WebSiparisMi, TahsilatDurumu, callback, asyncState);
        }
        
        private object[] OnEndSiparisBul(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.ElTerminali> retVal = ((RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1)(this)).EndSiparisBul(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSiparisBulCompleted(object state) {
            if ((this.SiparisBulCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SiparisBulCompleted(this, new SiparisBulCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SiparisBulAsync(bool WebSiparisMi, bool TahsilatDurumu) {
            this.SiparisBulAsync(WebSiparisMi, TahsilatDurumu, null);
        }
        
        public void SiparisBulAsync(bool WebSiparisMi, bool TahsilatDurumu, object userState) {
            if ((this.onBeginSiparisBulDelegate == null)) {
                this.onBeginSiparisBulDelegate = new BeginOperationDelegate(this.OnBeginSiparisBul);
            }
            if ((this.onEndSiparisBulDelegate == null)) {
                this.onEndSiparisBulDelegate = new EndOperationDelegate(this.OnEndSiparisBul);
            }
            if ((this.onSiparisBulCompletedDelegate == null)) {
                this.onSiparisBulCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSiparisBulCompleted);
            }
            base.InvokeAsync(this.onBeginSiparisBulDelegate, new object[] {
                        WebSiparisMi,
                        TahsilatDurumu}, this.onEndSiparisBulDelegate, this.onSiparisBulCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1>, RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<RestaurantOtomasyonu_ElTerminali.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginKullaniciGirisi(string KullaniciAdi, string Sifre, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = KullaniciAdi;
                _args[1] = Sifre;
                System.IAsyncResult _result = base.BeginInvoke("KullaniciGirisi", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.Tbl_Kullanicilar> EndKullaniciGirisi(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.Tbl_Kullanicilar> _result = ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.Tbl_Kullanicilar>)(base.EndInvoke("KullaniciGirisi", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSiparisBul(bool WebSiparisMi, bool TahsilatDurumu, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = WebSiparisMi;
                _args[1] = TahsilatDurumu;
                System.IAsyncResult _result = base.BeginInvoke("SiparisBul", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.ElTerminali> EndSiparisBul(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.ElTerminali> _result = ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_ElTerminali.ServiceReference1.ElTerminali>)(base.EndInvoke("SiparisBul", _args, result)));
                return _result;
            }
        }
    }
}
