//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tbl_Kullanicilar", Namespace="http://schemas.datacontract.org/2004/07/ElTerminaliService")]
    public partial class Tbl_Kullanicilar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresField;
        
        private System.Nullable<int> IDField;
        
        private string IsimField;
        
        private string KullaniciAdiField;
        
        private System.Nullable<int> KullaniciIDField;
        
        private string SifreField;
        
        private string SoyisimField;
        
        private System.Nullable<int> YetkiIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyisim {
            get {
                return this.SoyisimField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyisimField, value) != true)) {
                    this.SoyisimField = value;
                    this.RaisePropertyChanged("Soyisim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YetkiID {
            get {
                return this.YetkiIDField;
            }
            set {
                if ((this.YetkiIDField.Equals(value) != true)) {
                    this.YetkiIDField = value;
                    this.RaisePropertyChanged("YetkiID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiparisListesi", Namespace="http://schemas.datacontract.org/2004/07/ElTerminaliService")]
    public partial class SiparisListesi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AciklamaField;
        
        private int AdetField;
        
        private string AltMenuAdiField;
        
        private string EkIsteklerField;
        
        private int GenelToplamField;
        
        private string IsimField;
        
        private string MasaAdiField;
        
        private int MasaNoField;
        
        private string MenuAdiField;
        
        private string SiparisZamaniField;
        
        private string SoyisimField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Adet {
            get {
                return this.AdetField;
            }
            set {
                if ((this.AdetField.Equals(value) != true)) {
                    this.AdetField = value;
                    this.RaisePropertyChanged("Adet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltMenuAdi {
            get {
                return this.AltMenuAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AltMenuAdiField, value) != true)) {
                    this.AltMenuAdiField = value;
                    this.RaisePropertyChanged("AltMenuAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EkIstekler {
            get {
                return this.EkIsteklerField;
            }
            set {
                if ((object.ReferenceEquals(this.EkIsteklerField, value) != true)) {
                    this.EkIsteklerField = value;
                    this.RaisePropertyChanged("EkIstekler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenelToplam {
            get {
                return this.GenelToplamField;
            }
            set {
                if ((this.GenelToplamField.Equals(value) != true)) {
                    this.GenelToplamField = value;
                    this.RaisePropertyChanged("GenelToplam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasaAdi {
            get {
                return this.MasaAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MasaAdiField, value) != true)) {
                    this.MasaAdiField = value;
                    this.RaisePropertyChanged("MasaAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MasaNo {
            get {
                return this.MasaNoField;
            }
            set {
                if ((this.MasaNoField.Equals(value) != true)) {
                    this.MasaNoField = value;
                    this.RaisePropertyChanged("MasaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuAdi {
            get {
                return this.MenuAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuAdiField, value) != true)) {
                    this.MenuAdiField = value;
                    this.RaisePropertyChanged("MenuAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiparisZamani {
            get {
                return this.SiparisZamaniField;
            }
            set {
                if ((object.ReferenceEquals(this.SiparisZamaniField, value) != true)) {
                    this.SiparisZamaniField = value;
                    this.RaisePropertyChanged("SiparisZamani");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyisim {
            get {
                return this.SoyisimField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyisimField, value) != true)) {
                    this.SoyisimField = value;
                    this.RaisePropertyChanged("Soyisim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/KullaniciGirisi", ReplyAction="http://tempuri.org/IService1/KullaniciGirisiResponse")]
        System.IAsyncResult BeginKullaniciGirisi(string KullaniciAdi, string Sifre, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.Tbl_Kullanicilar> EndKullaniciGirisi(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SiparisListele", ReplyAction="http://tempuri.org/IService1/SiparisListeleResponse")]
        System.IAsyncResult BeginSiparisListele(bool MID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> EndSiparisListele(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SiparisHazirMiKontrolu", ReplyAction="http://tempuri.org/IService1/SiparisHazirMiKontroluResponse")]
        System.IAsyncResult BeginSiparisHazirMiKontrolu(bool SHM, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> EndSiparisHazirMiKontrolu(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/HesapIstendiMiKontrolu", ReplyAction="http://tempuri.org/IService1/HesapIstendiMiKontroluResponse")]
        System.IAsyncResult BeginHesapIstendiMiKontrolu(bool HIM, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> EndHesapIstendiMiKontrolu(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciGirisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public KullaniciGirisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.Tbl_Kullanicilar> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.Tbl_Kullanicilar>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiparisListeleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SiparisListeleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiparisHazirMiKontroluCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SiparisHazirMiKontroluCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HesapIstendiMiKontroluCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HesapIstendiMiKontroluCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1>, RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginKullaniciGirisiDelegate;
        
        private EndOperationDelegate onEndKullaniciGirisiDelegate;
        
        private System.Threading.SendOrPostCallback onKullaniciGirisiCompletedDelegate;
        
        private BeginOperationDelegate onBeginSiparisListeleDelegate;
        
        private EndOperationDelegate onEndSiparisListeleDelegate;
        
        private System.Threading.SendOrPostCallback onSiparisListeleCompletedDelegate;
        
        private BeginOperationDelegate onBeginSiparisHazirMiKontroluDelegate;
        
        private EndOperationDelegate onEndSiparisHazirMiKontroluDelegate;
        
        private System.Threading.SendOrPostCallback onSiparisHazirMiKontroluCompletedDelegate;
        
        private BeginOperationDelegate onBeginHesapIstendiMiKontroluDelegate;
        
        private EndOperationDelegate onEndHesapIstendiMiKontroluDelegate;
        
        private System.Threading.SendOrPostCallback onHesapIstendiMiKontroluCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<KullaniciGirisiCompletedEventArgs> KullaniciGirisiCompleted;
        
        public event System.EventHandler<SiparisListeleCompletedEventArgs> SiparisListeleCompleted;
        
        public event System.EventHandler<SiparisHazirMiKontroluCompletedEventArgs> SiparisHazirMiKontroluCompleted;
        
        public event System.EventHandler<HesapIstendiMiKontroluCompletedEventArgs> HesapIstendiMiKontroluCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1.BeginKullaniciGirisi(string KullaniciAdi, string Sifre, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginKullaniciGirisi(KullaniciAdi, Sifre, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.Tbl_Kullanicilar> RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1.EndKullaniciGirisi(System.IAsyncResult result) {
            return base.Channel.EndKullaniciGirisi(result);
        }
        
        private System.IAsyncResult OnBeginKullaniciGirisi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string KullaniciAdi = ((string)(inValues[0]));
            string Sifre = ((string)(inValues[1]));
            return ((RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1)(this)).BeginKullaniciGirisi(KullaniciAdi, Sifre, callback, asyncState);
        }
        
        private object[] OnEndKullaniciGirisi(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.Tbl_Kullanicilar> retVal = ((RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1)(this)).EndKullaniciGirisi(result);
            return new object[] {
                    retVal};
        }
        
        private void OnKullaniciGirisiCompleted(object state) {
            if ((this.KullaniciGirisiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KullaniciGirisiCompleted(this, new KullaniciGirisiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KullaniciGirisiAsync(string KullaniciAdi, string Sifre) {
            this.KullaniciGirisiAsync(KullaniciAdi, Sifre, null);
        }
        
        public void KullaniciGirisiAsync(string KullaniciAdi, string Sifre, object userState) {
            if ((this.onBeginKullaniciGirisiDelegate == null)) {
                this.onBeginKullaniciGirisiDelegate = new BeginOperationDelegate(this.OnBeginKullaniciGirisi);
            }
            if ((this.onEndKullaniciGirisiDelegate == null)) {
                this.onEndKullaniciGirisiDelegate = new EndOperationDelegate(this.OnEndKullaniciGirisi);
            }
            if ((this.onKullaniciGirisiCompletedDelegate == null)) {
                this.onKullaniciGirisiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKullaniciGirisiCompleted);
            }
            base.InvokeAsync(this.onBeginKullaniciGirisiDelegate, new object[] {
                        KullaniciAdi,
                        Sifre}, this.onEndKullaniciGirisiDelegate, this.onKullaniciGirisiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1.BeginSiparisListele(bool MID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSiparisListele(MID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1.EndSiparisListele(System.IAsyncResult result) {
            return base.Channel.EndSiparisListele(result);
        }
        
        private System.IAsyncResult OnBeginSiparisListele(object[] inValues, System.AsyncCallback callback, object asyncState) {
            bool MID = ((bool)(inValues[0]));
            return ((RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1)(this)).BeginSiparisListele(MID, callback, asyncState);
        }
        
        private object[] OnEndSiparisListele(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> retVal = ((RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1)(this)).EndSiparisListele(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSiparisListeleCompleted(object state) {
            if ((this.SiparisListeleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SiparisListeleCompleted(this, new SiparisListeleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SiparisListeleAsync(bool MID) {
            this.SiparisListeleAsync(MID, null);
        }
        
        public void SiparisListeleAsync(bool MID, object userState) {
            if ((this.onBeginSiparisListeleDelegate == null)) {
                this.onBeginSiparisListeleDelegate = new BeginOperationDelegate(this.OnBeginSiparisListele);
            }
            if ((this.onEndSiparisListeleDelegate == null)) {
                this.onEndSiparisListeleDelegate = new EndOperationDelegate(this.OnEndSiparisListele);
            }
            if ((this.onSiparisListeleCompletedDelegate == null)) {
                this.onSiparisListeleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSiparisListeleCompleted);
            }
            base.InvokeAsync(this.onBeginSiparisListeleDelegate, new object[] {
                        MID}, this.onEndSiparisListeleDelegate, this.onSiparisListeleCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1.BeginSiparisHazirMiKontrolu(bool SHM, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSiparisHazirMiKontrolu(SHM, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1.EndSiparisHazirMiKontrolu(System.IAsyncResult result) {
            return base.Channel.EndSiparisHazirMiKontrolu(result);
        }
        
        private System.IAsyncResult OnBeginSiparisHazirMiKontrolu(object[] inValues, System.AsyncCallback callback, object asyncState) {
            bool SHM = ((bool)(inValues[0]));
            return ((RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1)(this)).BeginSiparisHazirMiKontrolu(SHM, callback, asyncState);
        }
        
        private object[] OnEndSiparisHazirMiKontrolu(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> retVal = ((RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1)(this)).EndSiparisHazirMiKontrolu(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSiparisHazirMiKontroluCompleted(object state) {
            if ((this.SiparisHazirMiKontroluCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SiparisHazirMiKontroluCompleted(this, new SiparisHazirMiKontroluCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SiparisHazirMiKontroluAsync(bool SHM) {
            this.SiparisHazirMiKontroluAsync(SHM, null);
        }
        
        public void SiparisHazirMiKontroluAsync(bool SHM, object userState) {
            if ((this.onBeginSiparisHazirMiKontroluDelegate == null)) {
                this.onBeginSiparisHazirMiKontroluDelegate = new BeginOperationDelegate(this.OnBeginSiparisHazirMiKontrolu);
            }
            if ((this.onEndSiparisHazirMiKontroluDelegate == null)) {
                this.onEndSiparisHazirMiKontroluDelegate = new EndOperationDelegate(this.OnEndSiparisHazirMiKontrolu);
            }
            if ((this.onSiparisHazirMiKontroluCompletedDelegate == null)) {
                this.onSiparisHazirMiKontroluCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSiparisHazirMiKontroluCompleted);
            }
            base.InvokeAsync(this.onBeginSiparisHazirMiKontroluDelegate, new object[] {
                        SHM}, this.onEndSiparisHazirMiKontroluDelegate, this.onSiparisHazirMiKontroluCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1.BeginHesapIstendiMiKontrolu(bool HIM, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHesapIstendiMiKontrolu(HIM, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1.EndHesapIstendiMiKontrolu(System.IAsyncResult result) {
            return base.Channel.EndHesapIstendiMiKontrolu(result);
        }
        
        private System.IAsyncResult OnBeginHesapIstendiMiKontrolu(object[] inValues, System.AsyncCallback callback, object asyncState) {
            bool HIM = ((bool)(inValues[0]));
            return ((RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1)(this)).BeginHesapIstendiMiKontrolu(HIM, callback, asyncState);
        }
        
        private object[] OnEndHesapIstendiMiKontrolu(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> retVal = ((RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1)(this)).EndHesapIstendiMiKontrolu(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHesapIstendiMiKontroluCompleted(object state) {
            if ((this.HesapIstendiMiKontroluCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HesapIstendiMiKontroluCompleted(this, new HesapIstendiMiKontroluCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HesapIstendiMiKontroluAsync(bool HIM) {
            this.HesapIstendiMiKontroluAsync(HIM, null);
        }
        
        public void HesapIstendiMiKontroluAsync(bool HIM, object userState) {
            if ((this.onBeginHesapIstendiMiKontroluDelegate == null)) {
                this.onBeginHesapIstendiMiKontroluDelegate = new BeginOperationDelegate(this.OnBeginHesapIstendiMiKontrolu);
            }
            if ((this.onEndHesapIstendiMiKontroluDelegate == null)) {
                this.onEndHesapIstendiMiKontroluDelegate = new EndOperationDelegate(this.OnEndHesapIstendiMiKontrolu);
            }
            if ((this.onHesapIstendiMiKontroluCompletedDelegate == null)) {
                this.onHesapIstendiMiKontroluCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHesapIstendiMiKontroluCompleted);
            }
            base.InvokeAsync(this.onBeginHesapIstendiMiKontroluDelegate, new object[] {
                        HIM}, this.onEndHesapIstendiMiKontroluDelegate, this.onHesapIstendiMiKontroluCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1>, RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginKullaniciGirisi(string KullaniciAdi, string Sifre, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = KullaniciAdi;
                _args[1] = Sifre;
                System.IAsyncResult _result = base.BeginInvoke("KullaniciGirisi", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.Tbl_Kullanicilar> EndKullaniciGirisi(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.Tbl_Kullanicilar> _result = ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.Tbl_Kullanicilar>)(base.EndInvoke("KullaniciGirisi", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSiparisListele(bool MID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = MID;
                System.IAsyncResult _result = base.BeginInvoke("SiparisListele", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> EndSiparisListele(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> _result = ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi>)(base.EndInvoke("SiparisListele", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSiparisHazirMiKontrolu(bool SHM, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = SHM;
                System.IAsyncResult _result = base.BeginInvoke("SiparisHazirMiKontrolu", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> EndSiparisHazirMiKontrolu(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> _result = ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi>)(base.EndInvoke("SiparisHazirMiKontrolu", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHesapIstendiMiKontrolu(bool HIM, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = HIM;
                System.IAsyncResult _result = base.BeginInvoke("HesapIstendiMiKontrolu", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> EndHesapIstendiMiKontrolu(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi> _result = ((System.Collections.ObjectModel.ObservableCollection<RestaurantOtomasyonu_GarsonElTerminali.ServiceReference1.SiparisListesi>)(base.EndInvoke("HesapIstendiMiKontrolu", _args, result)));
                return _result;
            }
        }
    }
}
