#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTerminaliService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RestaurantOtomasyonu")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RestaurantOtomasyonuConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_AltMenuler> Tbl_AltMenulers
		{
			get
			{
				return this.GetTable<Tbl_AltMenuler>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_AnaMenuler> Tbl_AnaMenulers
		{
			get
			{
				return this.GetTable<Tbl_AnaMenuler>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Kullanicilar> Tbl_Kullanicilars
		{
			get
			{
				return this.GetTable<Tbl_Kullanicilar>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Siparisler> Tbl_Siparislers
		{
			get
			{
				return this.GetTable<Tbl_Siparisler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_AltMenuler")]
	public partial class Tbl_AltMenuler
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _AltMenuID;
		
		private string _AltMenuAdi;
		
		private System.Nullable<int> _Fiyat;
		
		private System.Nullable<int> _AnaMenuID;
		
		public Tbl_AltMenuler()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltMenuID", DbType="Int")]
		public System.Nullable<int> AltMenuID
		{
			get
			{
				return this._AltMenuID;
			}
			set
			{
				if ((this._AltMenuID != value))
				{
					this._AltMenuID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltMenuAdi", DbType="NVarChar(100)")]
		public string AltMenuAdi
		{
			get
			{
				return this._AltMenuAdi;
			}
			set
			{
				if ((this._AltMenuAdi != value))
				{
					this._AltMenuAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Int")]
		public System.Nullable<int> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this._Fiyat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnaMenuID", DbType="Int")]
		public System.Nullable<int> AnaMenuID
		{
			get
			{
				return this._AnaMenuID;
			}
			set
			{
				if ((this._AnaMenuID != value))
				{
					this._AnaMenuID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_AnaMenuler")]
	public partial class Tbl_AnaMenuler
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _MenuID;
		
		private string _MenuAdi;
		
		public Tbl_AnaMenuler()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuID", DbType="Int")]
		public System.Nullable<int> MenuID
		{
			get
			{
				return this._MenuID;
			}
			set
			{
				if ((this._MenuID != value))
				{
					this._MenuID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuAdi", DbType="NVarChar(100)")]
		public string MenuAdi
		{
			get
			{
				return this._MenuAdi;
			}
			set
			{
				if ((this._MenuAdi != value))
				{
					this._MenuAdi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Kullanicilar")]
	public partial class Tbl_Kullanicilar
	{
		
		private System.Nullable<int> _ID;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
		private string _Isim;
		
		private string _Soyisim;
		
		private string _Adres;
		
		private System.Nullable<int> _YetkiID;
		
		private System.Nullable<int> _KullaniciID;
		
		public Tbl_Kullanicilar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="VarChar(100)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this._KullaniciAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="VarChar(100)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this._Sifre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isim", DbType="NVarChar(100)")]
		public string Isim
		{
			get
			{
				return this._Isim;
			}
			set
			{
				if ((this._Isim != value))
				{
					this._Isim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyisim", DbType="NVarChar(100)")]
		public string Soyisim
		{
			get
			{
				return this._Soyisim;
			}
			set
			{
				if ((this._Soyisim != value))
				{
					this._Soyisim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(200)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this._Adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiID", DbType="Int")]
		public System.Nullable<int> YetkiID
		{
			get
			{
				return this._YetkiID;
			}
			set
			{
				if ((this._YetkiID != value))
				{
					this._YetkiID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciID", DbType="Int")]
		public System.Nullable<int> KullaniciID
		{
			get
			{
				return this._KullaniciID;
			}
			set
			{
				if ((this._KullaniciID != value))
				{
					this._KullaniciID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Siparisler")]
	public partial class Tbl_Siparisler
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _SiparisID;
		
		private System.Nullable<int> _MenuID;
		
		private System.Nullable<int> _AltMenuID;
		
		private System.Nullable<int> _Adet;
		
		private System.Nullable<int> _Fiyat;
		
		private string _SiparisZamani;
		
		private string _Aciklama;
		
		private string _EkIstekler;
		
		private System.Nullable<int> _MasaID;
		
		private System.Nullable<int> _KullaniciID;
		
		private System.Nullable<int> _GenelToplam;
		
		private System.Nullable<bool> _TahsilatDurumu;
		
		private System.Nullable<bool> _WebSiparisiMi;
		
		private System.Nullable<int> _TahsilatYapanKullaniciID;
		
		private System.Nullable<bool> _MasaSiparisiMi;
		
		private System.Nullable<bool> _SiparisHazirMi;
		
		private System.Nullable<bool> _HesapIstendiMi;
		
		public Tbl_Siparisler()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiparisID", DbType="Int")]
		public System.Nullable<int> SiparisID
		{
			get
			{
				return this._SiparisID;
			}
			set
			{
				if ((this._SiparisID != value))
				{
					this._SiparisID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuID", DbType="Int")]
		public System.Nullable<int> MenuID
		{
			get
			{
				return this._MenuID;
			}
			set
			{
				if ((this._MenuID != value))
				{
					this._MenuID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltMenuID", DbType="Int")]
		public System.Nullable<int> AltMenuID
		{
			get
			{
				return this._AltMenuID;
			}
			set
			{
				if ((this._AltMenuID != value))
				{
					this._AltMenuID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="Int")]
		public System.Nullable<int> Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this._Adet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Int")]
		public System.Nullable<int> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this._Fiyat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiparisZamani", DbType="VarChar(100)")]
		public string SiparisZamani
		{
			get
			{
				return this._SiparisZamani;
			}
			set
			{
				if ((this._SiparisZamani != value))
				{
					this._SiparisZamani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(200)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this._Aciklama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EkIstekler", DbType="NVarChar(200)")]
		public string EkIstekler
		{
			get
			{
				return this._EkIstekler;
			}
			set
			{
				if ((this._EkIstekler != value))
				{
					this._EkIstekler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasaID", DbType="Int")]
		public System.Nullable<int> MasaID
		{
			get
			{
				return this._MasaID;
			}
			set
			{
				if ((this._MasaID != value))
				{
					this._MasaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciID", DbType="Int")]
		public System.Nullable<int> KullaniciID
		{
			get
			{
				return this._KullaniciID;
			}
			set
			{
				if ((this._KullaniciID != value))
				{
					this._KullaniciID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenelToplam", DbType="Int")]
		public System.Nullable<int> GenelToplam
		{
			get
			{
				return this._GenelToplam;
			}
			set
			{
				if ((this._GenelToplam != value))
				{
					this._GenelToplam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TahsilatDurumu", DbType="Bit")]
		public System.Nullable<bool> TahsilatDurumu
		{
			get
			{
				return this._TahsilatDurumu;
			}
			set
			{
				if ((this._TahsilatDurumu != value))
				{
					this._TahsilatDurumu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebSiparisiMi", DbType="Bit")]
		public System.Nullable<bool> WebSiparisiMi
		{
			get
			{
				return this._WebSiparisiMi;
			}
			set
			{
				if ((this._WebSiparisiMi != value))
				{
					this._WebSiparisiMi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TahsilatYapanKullaniciID", DbType="Int")]
		public System.Nullable<int> TahsilatYapanKullaniciID
		{
			get
			{
				return this._TahsilatYapanKullaniciID;
			}
			set
			{
				if ((this._TahsilatYapanKullaniciID != value))
				{
					this._TahsilatYapanKullaniciID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasaSiparisiMi", DbType="Bit")]
		public System.Nullable<bool> MasaSiparisiMi
		{
			get
			{
				return this._MasaSiparisiMi;
			}
			set
			{
				if ((this._MasaSiparisiMi != value))
				{
					this._MasaSiparisiMi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiparisHazirMi", DbType="Bit")]
		public System.Nullable<bool> SiparisHazirMi
		{
			get
			{
				return this._SiparisHazirMi;
			}
			set
			{
				if ((this._SiparisHazirMi != value))
				{
					this._SiparisHazirMi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesapIstendiMi", DbType="Bit")]
		public System.Nullable<bool> HesapIstendiMi
		{
			get
			{
				return this._HesapIstendiMi;
			}
			set
			{
				if ((this._HesapIstendiMi != value))
				{
					this._HesapIstendiMi = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
